### ISSUE TITLE
Error in running turtle_tf2 demo launch files

### ISSUE THREAD

**Issue by qboticslabs** [ros/geometry_tutorials#30]
Hello

Getting the python env error when we run the demo launch files

/usr/bin/env: process[turtle_pointer-5]: started with pid [4834]
‘python’: No such file or directory
[turtle_pointer-5] process has died [pi

Regards

**Comment by felixvd** [comment]
You need to install python or set up your environment correctly.

**Comment by clalancette** [comment]
Closing this as stale.
