### ISSUE TITLE
Maintainer  ros2 branch

### ISSUE THREAD

**Issue by ahcorde** [ros/geometry_tutorials#42]
Hi @destogl,

I noticed that you are the maintaner of the ROS 1 version of geometry_tutorials. We have created a ros2 branch of this packages. Are you interested of being a maintaner too ?

FYI @audrow

**Comment by kennywangaigraphx** [comment]
Hi @ahcorde,
     I'm studying tf2 these days, and I migrated some tf2 tutorials on http://wiki.ros.org/tf2/Tutorials from ros1 to ros2, including: (1)learning about tf2 and time (C++)(Python); (2)time travel with tf2 (C++)(Python); (3)Basic Debugging tf2; (4)Using Stamped datatypes with tf2_ros::MessageFilter. Can I be a contributor?

**Comment by kurshakuz** [comment]
Hello @kennywangaigraphx! I am currently actively working on these tutorials, and we have already "Learning about tf2 and time" and "Time travel with tf2" tutorials ready. But your work on "Basic Debugging tf2" and "Using Stamped datatypes with tf2_ros::MessageFilter" can help us a lot! 

Please feel free to open a corresponding PR to the https://github.com/ros2/ros2_documentation repository. For now you can open a PR to `rolling` branch and we will backport to other versions. Don't hesitate to ask us or open an issue if one appears in the process.

**Comment by kennywangaigraphx** [comment]
Hi@kurshakuz. Ok, I'll try my best to do that, because I am a newer to Github and Git， I need some time to learn how to create a  PR.

**Comment by clalancette** [comment]
I'm going to go ahead and close this issue, since there isn't really any action to take here.  Feel free to reopen if you disagree.
